.TH ADDUSER 1

.SH NAME
adduser \- adds user to the system

.SH SYNOPSIS
.B adduser
[\fB\-n\fR \fIBITS\fR]
[\fB\-\-bits\fR \fIBITS\fR]
.IR file ...

.SH DESCRIPTION
.B adduser
adduser adds a local user to the system.

.SH OPTIONS
.TP
.BR \-h ", " \-\-user =\fIUSERNAME\fR
Check if a user already exists before executing the command to add a user.
